<?php

namespace StatisticsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NormalizedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NormalizedDataRepository extends EntityRepository
{
}
