parameters:

services:
    statistics.geolocator:
        class: StatisticsBundle\Utility\Geolocator

    clusterpoint:
        class: AppBundle\Clusterpoint\ClusterpointConnectionFactory
        arguments:
            - %cp_name%
            - %cp_password%
            - %cp_address%
            - %cp_id%
